version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile-back
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - message-broker
    environment:
      - DB_PASSWORD=54321
    networks:
      - monitoring_network
    restart: always
  pinger:
    build: 
      context: .
      dockerfile: ./pinger/Dockerfile-ping
    container_name: pinger
    networks:
      - monitoring_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    command: ["sh", "-c", "sleep 10 && /go/bin/pinger"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-front
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - message-broker
    networks:
      - monitoring_network
    restart: unless-stopped
  db:
    container_name: db
    restart: always
    image: postgres:latest
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=54321
    networks:
      - monitoring_network
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s
    
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    ports:
      - 5672:5672   
      - 15672:15672 
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - monitoring_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  monitoring_network:
    name: monitoring_network
    driver: bridge