FROM golang:1.22

WORKDIR /app
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    && curl -fsSL https://get.docker.com | sh \
    && apt-get install -y docker-ce-cli

COPY go.mod go.sum ./
RUN go mod download

COPY pinger ./pinger
COPY ./pkg/logging /app/pkg/logging

RUN go build -o /go/bin/pinger ./pinger/cmd/main.go

EXPOSE 8001

CMD ["/go/bin/pinger"]